# Generated by Django 5.1.4 on 2024-12-08 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre único del usuario, máximo 30 caracteres.', max_length=30, unique=True, verbose_name='Nombre de usuario')),
                ('password', models.CharField(help_text='Contraseña del usuario, entre 6 y 30 caracteres.', max_length=30, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Contraseña')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Género del usuario (M: Masculino, F: Femenino).', max_length=1, verbose_name='Género')),
                ('nacimiento', models.DateField(help_text='Fecha de nacimiento del usuario en formato DD-MM-YYYY.', verbose_name='Fecha de nacimiento')),
                ('puntos', models.PositiveIntegerField(default=0, help_text='Puntos acumulados por el usuario.', verbose_name='Puntos')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
