# Generated by Django 5.1.4 on 2024-12-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True),
        ),
    ]
