# Generated by Django 5.1.4 on 2025-01-03 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(limit_choices_to={'user_type': 'business'}, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
                'unique_together': {('negocio', 'nombre', 'apellido')},
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_temporal', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('encuesta_completada', models.BooleanField(default=False)),
                ('sentimiento', models.CharField(blank=True, choices=[('POS', 'Positivo'), ('NEU', 'Neutral'), ('NEG', 'Negativo')], max_length=3, null=True)),
                ('tipo_cliente', models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('recurrente', 'Recurrente'), ('ocasional', 'Ocasional')], max_length=20)),
                ('respuesta_anonima', models.BooleanField(default=False)),
                ('experiencia_general', models.IntegerField(blank=True, null=True)),
                ('atencion_servicio', models.IntegerField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('hashtag', models.CharField(blank=True, help_text='Una palabra que defina tu experiencia (sin el símbolo #)', max_length=30, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encuestas', to='encuestas.empleado')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_negocio', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
