# Generated by Django 5.1.4 on 2024-12-06 00:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.CharField(max_length=100)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('usada', models.BooleanField(default=False)),
            ],
        ),
    ]
