# Generated by Django 5.1.4 on 2024-12-19 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia_general', models.IntegerField(blank=True, null=True)),
                ('atencion_servicio', models.IntegerField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('tipo_cliente', models.CharField(blank=True, choices=[('primera', 'Primera vez'), ('frecuente', 'Cliente frecuente'), ('ocasional', 'Cliente ocasional')], max_length=20, null=True)),
                ('respuesta_anonima', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('codigo_temporal', models.CharField(blank=True, max_length=4, null=True)),
                ('encuesta_completada', models.BooleanField(default=False)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('sentimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('confianza_sentimiento', models.FloatField(blank=True, null=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_negocio', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
