# Generated by Django 5.1.4 on 2024-12-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='atencion_servicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='experiencia_general',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('primera', 'Primera vez'), ('frecuente', 'Cliente frecuente'), ('ocasional', 'Cliente ocasional')], max_length=20, null=True),
        ),
    ]
