# Generated by Django 5.1.4 on 2024-12-19 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='confianza_sentimiento',
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='codigo_temporal',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_expiracion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='sentimiento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('recurrente', 'Recurrente'), ('ocasional', 'Ocasional')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
