# Generated by Django 5.1.4 on 2024-12-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='sentimiento',
            field=models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('neutral', 'Neutral')], help_text='Sentimiento detectado en las recomendaciones', max_length=10, null=True),
        ),
    ]
