# Generated by Django 5.1.4 on 2024-12-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_alter_encuesta_sentimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='sentimiento',
            field=models.CharField(blank=True, choices=[('POS', 'Positivo'), ('NEU', 'Neutral'), ('NEG', 'Negativo')], max_length=3, null=True),
        ),
    ]
