# Generated by Django 5.1.4 on 2024-12-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_alter_encuesta_atencion_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='confianza_sentimiento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='sentimiento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
