# Generated by Django 5.1.4 on 2024-12-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_alter_encuesta_sentimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='tipo_cliente',
            field=models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('recurrente', 'Recurrente'), ('ocasional', 'Ocasional')], max_length=20),
        ),
    ]
